In [33]:
# Load packages
library("plotly")
library("tidyverse")
library("data.table")
library("gridExtra")
library("knitr")

# Load athletes_events data 
data <- read_csv("120-years-of-olympic-history-athletes-and-results/athlete_events.csv",
                 col_types = cols(
                   ID = col_character(),
                   Name = col_character(),
                   Sex = col_factor(levels = c("M","F")),
                   Age =  col_integer(),
                   Height = col_double(),
                   Weight = col_double(),
                   Team = col_character(),
                   NOC = col_character(),
                   Games = col_character(),
                   Year = col_integer(),
                   Season = col_factor(levels = c("Summer","Winter")),
                   City = col_character(),
                   Sport = col_character(),
                   Event = col_character(),
                   Medal = col_factor(levels = c("Gold","Silver","Bronze"))
                 )
)

In [27]:
# 1 question count the number of athletes
data

       ID     Name                               Sex Age Height Weight
1      1      A Dijiang                          M   24  180    80
2      2      A Lamusi                           M   23  170    60
3      3      Gunnar Nielsen Aaby                M   24   NA    NA
4      4      Edgar Lindenau Aabye               M   34   NA    NA
5      5      Christine Jacoba Aaftink           F   21  185    82
6      5      Christine Jacoba Aaftink           F   21  185    82
7      5      Christine Jacoba Aaftink           F   25  185    82
8      5      Christine Jacoba Aaftink           F   25  185    82
9      5      Christine Jacoba Aaftink           F   27  185    82
10     5      Christine Jacoba Aaftink           F   27  185    82
11     6      Per Knut Aaland                    M   31  188    75
12     6      Per Knut Aaland                    M   31  188    75
13     6      Per Knut Aaland                    M   31  188    75
14     6      Per Knut Aaland                    M   31  188    75
15     6      Per Knut Aaland                    M   33  188    75
16     6      Per Knut Aaland                    M   33  188    75
17     6      Per Knut Aaland                    M   33  188    75
18     6      Per Knut Aaland                    M   33  188    75
19     7      John Aalberg                       M   31  183    72
20     7      John Aalberg                       M   31  183    72
21     7      John Aalberg                       M   31  183    72
22     7      John Aalberg                       M   31  183    72
23     7      John Aalberg                       M   33  183    72
24     7      John Aalberg                       M   33  183    72
25     7      John Aalberg                       M   33  183    72
26     7      John Aalberg                       M   33  183    72
27     8      Cornelia "Cor" Aalten (-Strannood) F   18  168    NA
28     8      Cornelia "Cor" Aalten (-Strannood) F   18  168    NA
29     9      Antti Sami Aalto                   M   26  186    96
30     10     Einar Ferdinand "Einari" Aalto     M   26   NA    NA
â‹®      â‹®      â‹®                                  â‹®   â‹®   â‹®      â‹®
271087 135555 Micha Zych                         M   23  177    68
271088 135556 Bogusaw Stanisaw Zychowicz         M   19  189    80
271089 135556 Bogusaw Stanisaw Zychowicz         M   19  189    80
271090 135557 Dominik ycki                       M   34  192    95
271091 135557 Dominik ycki                       M   38  192    95
271092 135558 ukasz Tomasz ygado                 M   32  200    89
271093 135559 Pawe Jan Zygmunt                   M   21  182    79
271094 135559 Pawe Jan Zygmunt                   M   21  182    79
271095 135559 Pawe Jan Zygmunt                   M   25  182    79
271096 135559 Pawe Jan Zygmunt                   M   25  182    79
271097 135559 Pawe Jan Zygmunt                   M   29  182    79
271098 135559 Pawe Jan Zygmunt                   M   29  182    79
271099 135559 Pawe Jan Zygmunt                   M   33  182    79
271100 135560 Stavroula Zygouri                  F   36  171    63
271101 135561 Frantiek Zyka                      M   26   NA    NA
271102 135562 Milan Zyka                         M   24  173    68
271103 135563 Olesya Nikolayevna Zykina          F   19  171    64
271104 135563 Olesya Nikolayevna Zykina          F   23  171    64
271105 135564 Yevgeny Aleksandrovich Zykov       M   22  172    65
271106 135565 Fernando scar Zylberberg           M   23  168    76
271107 135565 Fernando scar Zylberberg           M   27  168    76
271108 135566 James Francis "Jim" Zylker         M   21  175    75
271109 135567 Aleksandr Viktorovich Zyuzin       M   24  183    72
271110 135567 Aleksandr Viktorovich Zyuzin       M   28  183    72
271111 135568 Olga Igorevna Zyuzkova             F   33  171    69
271112 135569 Andrzej ya                         M   29  179    89
271113 135570 Piotr ya                           M   27  176    59
271114 135570 Piotr ya                           M   27  176    59
271115 135571 Tomasz Ireneusz ya                 M   30  185    96
271116 135571 Tomasz Ireneusz ya                 M   34  185    96
       Team           NOC Games       Year Season City
1      China          CHN 1992 Summer 1992 Summer Barcelona
2      China          CHN 2012 Summer 2012 Summer London
3      Denmark        DEN 1920 Summer 1920 Summer Antwerpen
4      Denmark/Sweden DEN 1900 Summer 1900 Summer Paris
5      Netherlands    NED 1988 Winter 1988 Winter Calgary
6      Netherlands    NED 1988 Winter 1988 Winter Calgary
7      Netherlands    NED 1992 Winter 1992 Winter Albertville
8      Netherlands    NED 1992 Winter 1992 Winter Albertville
9      Netherlands    NED 1994 Winter 1994 Winter Lillehammer
10     Netherlands    NED 1994 Winter 1994 Winter Lillehammer
11     United States  USA 1992 Winter 1992 Winter Albertville
12     United States  USA 1992 Winter 1992 Winter Albertville
13     United States  USA 1992 Winter 1992 Winter Albertville
14     United States  USA 1992 Winter 1992 Winter Albertville
15     United States  USA 1994 Winter 1994 Winter Lillehammer
16     United States  USA 1994 Winter 1994 Winter Lillehammer
17     United States  USA 1994 Winter 1994 Winter Lillehammer
18     United States  USA 1994 Winter 1994 Winter Lillehammer
19     United States  USA 1992 Winter 1992 Winter Albertville
20     United States  USA 1992 Winter 1992 Winter Albertville
21     United States  USA 1992 Winter 1992 Winter Albertville
22     United States  USA 1992 Winter 1992 Winter Albertville
23     United States  USA 1994 Winter 1994 Winter Lillehammer
24     United States  USA 1994 Winter 1994 Winter Lillehammer
25     United States  USA 1994 Winter 1994 Winter Lillehammer
26     United States  USA 1994 Winter 1994 Winter Lillehammer
27     Netherlands    NED 1932 Summer 1932 Summer Los Angeles
28     Netherlands    NED 1932 Summer 1932 Summer Los Angeles
29     Finland        FIN 2002 Winter 2002 Winter Salt Lake City
30     Finland        FIN 1952 Summer 1952 Summer Helsinki
â‹®      â‹®              â‹®   â‹®           â‹®    â‹®      â‹®
271087 Poland         POL 2006 Winter 2006 Winter Torino
271088 Poland         POL 1980 Summer 1980 Summer Moskva
271089 Poland         POL 1980 Summer 1980 Summer Moskva
271090 Poland         POL 2008 Summer 2008 Summer Beijing
271091 Poland         POL 2012 Summer 2012 Summer London
271092 Poland         POL 2012 Summer 2012 Summer London
271093 Poland         POL 1994 Winter 1994 Winter Lillehammer
271094 Poland         POL 1994 Winter 1994 Winter Lillehammer
271095 Poland         POL 1998 Winter 1998 Winter Nagano
271096 Poland         POL 1998 Winter 1998 Winter Nagano
271097 Poland         POL 2002 Winter 2002 Winter Salt Lake City
271098 Poland         POL 2002 Winter 2002 Winter Salt Lake City
271099 Poland         POL 2006 Winter 2006 Winter Torino
271100 Greece         GRE 2004 Summer 2004 Summer Athina
271101 Czechoslovakia TCH 1928 Summer 1928 Summer Amsterdam
271102 Czechoslovakia TCH 1972 Summer 1972 Summer Munich
271103 Russia         RUS 2000 Summer 2000 Summer Sydney
271104 Russia         RUS 2004 Summer 2004 Summer Athina
271105 Russia-1       RUS 2002 Winter 2002 Winter Salt Lake City
271106 Argentina      ARG 2000 Summer 2000 Summer Sydney
271107 Argentina      ARG 2004 Summer 2004 Summer Athina
271108 United States  USA 1972 Summer 1972 Summer Munich
271109 Russia         RUS 2000 Summer 2000 Summer Sydney
271110 Russia         RUS 2004 Summer 2004 Summer Athina
271111 Belarus        BLR 2016 Summer 2016 Summer Rio de Janeiro
271112 Poland-1       POL 1976 Winter 1976 Winter Innsbruck
271113 Poland         POL 2014 Winter 2014 Winter Sochi
271114 Poland         POL 2014 Winter 2014 Winter Sochi
271115 Poland         POL 1998 Winter 1998 Winter Nagano
271116 Poland         POL 2002 Winter 2002 Winter Salt Lake City
       Sport                Event
1      Basketball           Basketball Men's Basketball
2      Judo                 Judo Men's Extra-Lightweight
3      Football             Football Men's Football
4      Tug-Of-War           Tug-Of-War Men's Tug-Of-War
5      Speed Skating        Speed Skating Women's 500 metres
6      Speed Skating        Speed Skating Women's 1,000 metres
7      Speed Skating        Speed Skating Women's 500 metres
8      Speed Skating        Speed Skating Women's 1,000 metres
9      Speed Skating        Speed Skating Women's 500 metres
10     Speed Skating        Speed Skating Women's 1,000 metres
11     Cross Country Skiing Cross Country Skiing Men's 10 kilometres
12     Cross Country Skiing Cross Country Skiing Men's 50 kilometres
13     Cross Country Skiing Cross Country Skiing Men's 10/15 kilometres Pursuit
14     Cross Country Skiing Cross Country Skiing Men's 4 x 10 kilometres Relay
15     Cross Country Skiing Cross Country Skiing Men's 10 kilometres
16     Cross Country Skiing Cross Country Skiing Men's 30 kilometres
17     Cross Country Skiing Cross Country Skiing Men's 10/15 kilometres Pursuit
18     Cross Country Skiing Cross Country Skiing Men's 4 x 10 kilometres Relay
19     Cross Country Skiing Cross Country Skiing Men's 10 kilometres
20     Cross Country Skiing Cross Country Skiing Men's 50 kilometres
21     Cross Country Skiing Cross Country Skiing Men's 10/15 kilometres Pursuit
22     Cross Country Skiing Cross Country Skiing Men's 4 x 10 kilometres Relay
23     Cross Country Skiing Cross Country Skiing Men's 10 kilometres
24     Cross Country Skiing Cross Country Skiing Men's 30 kilometres
25     Cross Country Skiing Cross Country Skiing Men's 10/15 kilometres Pursuit
26     Cross Country Skiing Cross Country Skiing Men's 4 x 10 kilometres Relay
27     Athletics            Athletics Women's 100 metres
28     Athletics            Athletics Women's 4 x 100 metres Relay
29     Ice Hockey           Ice Hockey Men's Ice Hockey
30     Swimming             Swimming Men's 400 metres Freestyle
â‹®      â‹®                    â‹®
271087 Figure Skating       Figure Skating Mixed Ice Dancing
271088 Swimming             Swimming Men's 100 metres Butterfly
271089 Swimming             Swimming Men's 200 metres Butterfly
271090 Sailing              Sailing Men's Two Person Keelboat
271091 Sailing              Sailing Men's Two Person Keelboat
271092 Volleyball           Volleyball Men's Volleyball
271093 Speed Skating        Speed Skating Men's 1,500 metres
271094 Speed Skating        Speed Skating Men's 5,000 metres
271095 Speed Skating        Speed Skating Men's 1,500 metres
271096 Speed Skating        Speed Skating Men's 5,000 metres
271097 Speed Skating        Speed Skating Men's 5,000 metres
271098 Speed Skating        Speed Skating Men's 10,000 metres
271099 Speed Skating        Speed Skating Men's 5,000 metres
271100 Wrestling            Wrestling Women's Middleweight, Freestyle
271101 Athletics            Athletics Men's Marathon
271102 Cycling              Cycling Men's Team Pursuit, 4,000 metres
271103 Athletics            Athletics Women's 4 x 400 metres Relay
271104 Athletics            Athletics Women's 4 x 400 metres Relay
271105 Luge                 Luge Mixed (Men)'s Doubles
271106 Hockey               Hockey Men's Hockey
271107 Hockey               Hockey Men's Hockey
271108 Football             Football Men's Football
271109 Rowing               Rowing Men's Lightweight Coxless Fours
271110 Rowing               Rowing Men's Lightweight Coxless Fours
271111 Basketball           Basketball Women's Basketball
271112 Luge                 Luge Mixed (Men)'s Doubles
271113 Ski Jumping          Ski Jumping Men's Large Hill, Individual
271114 Ski Jumping          Ski Jumping Men's Large Hill, Team
271115 Bobsleigh            Bobsleigh Men's Four
271116 Bobsleigh            Bobsleigh Men's Four
       Medal
1      NA
2      NA
3      NA
4      Gold
5      NA
6      NA
7      NA
8      NA
9      NA
10     NA
11     NA
12     NA
13     NA
14     NA
15     NA
16     NA
17     NA
18     NA
19     NA
20     NA
21     NA
22     NA
23     NA
24     NA
25     NA
26     NA
27     NA
28     NA
29     NA
30     NA
â‹®      â‹®
271087 NA
271088 NA
271089 NA
271090 NA
271091 NA
271092 NA
271093 NA
271094 NA
271095 NA
271096 NA
271097 NA
271098 NA
271099 NA
271100 NA
271101 NA
271102 NA
271103 Bronze
271104 Silver
271105 NA
271106 NA
271107 NA
271108 NA
271109 NA
271110 NA
271111 NA
271112 NA
271113 NA
271114 NA
271115 NA
271116 NA

In [34]:
data %>% group_by(Year) %>% summarise(Athletes = length(unique(ID))

ERROR: Error in parse(text = x, srcfile = src): <text>:2:0: fin d'entrÃ©e inattendue
1: head(data %>% group_by(Year) %>% summarise(Athletes = length(unique(ID)))
   ^

<div class="alert alert-success">
 <b>EXERCISE</b>:
 <ul>
        <li>Has the number of athletes, nations, and events changed over time?</li>
        <li>Number of men and women over time ?</li>
        <li>Number of women relative to men across countries ?</li>
        <li>Proportion of women on Olympic teams: 1936 ?</li>
        <li>Medal counts for women of different nations: 1936 ?</li>
        <li>Proportion of women on Olympic teams: 1976 ?</li>
        <li>Medal counts for women of different nations: 1976 ?</li>
        <li>Athlete height over time ?</li>
        <li>Athlete weight over time ?</li>

</ul> 

</div>

1.        Has the number of athletes, nations, and events changed over time?